name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: soham2002/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ soham2002 }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
